- hosts: controlplane
  vars_prompt:
    - name: "schedule_control_plane"
      prompt: "Would you like to schedule pods on your control-plane node - recommended for small clusters (yes/no)?"
      private: no

  tasks:
    - name: create kubeadm init config file for setting cgroup driver + pod network subnet
      copy:
        dest: "/tmp/config.yaml"
        content: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          cgroupDriver: systemd
          ---
          apiVersion: kubeadm.k8s.io/v1beta2
          kind: ClusterConfiguration
          networking:
            podSubnet: 10.244.0.0/16

    - name: initialize the cluster
      become: yes
      shell: kubeadm init --cri-socket /run/containerd/containerd.sock --config /tmp/config.yaml

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_env.USER }}"
      become: yes
    
    - name: enable ability to schedule pods on the control-plane node (master)
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-
      when: schedule_control_plane | bool

    - name: install pod network add-on
      shell: kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
