- hosts: controlplane
  become: no
  vars_prompt:
    - name: "metallb_ip_range"
      prompt: "What IP would you like to use for MetalLB? e.g. '192.168.1.240-192.168.1.250'?"
      private: no
  tasks:

    # Install Helm - https://helm.sh/
    - name: add helm key
      become: yes
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: add helm repo
      become: yes
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm
    
    - name: install helm
      become: yes
      apt:
        name: helm
        state: present
        update_cache: yes

    # Install MetalLB - https://metallb.universe.tf/
    - name: enable strictARP for MetalLB
      shell: >
        kubectl get configmap kube-proxy -n kube-system -o yaml | \
        sed -e "s/strictARP: false/strictARP: true/" | \
        kubectl apply -f - -n kube-system
    
    - name: create MetalLB namespace
      shell: kubectl apply -f -
      args:
        stdin: |
          apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              app: metallb
              pod-security.kubernetes.io/enforce: privileged
              pod-security.kubernetes.io/audit: privileged
              pod-security.kubernetes.io/warn: privileged
            name: metallb-system

    - name: add MetalLB helm repo
      shell: helm repo add metallb https://metallb.github.io/metallb

    - name: run helm update
      shell: helm repo update

    - name: install MetalLB and wait for it to complete
      shell: helm upgrade --install metallb metallb/metallb --namespace metallb-system --wait
   
    - name: apply MetalLB config
      shell: kubectl apply -f -
      args:
        stdin: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
            - {{ metallb_ip_range }}
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: example
            namespace: metallb-system

    - name: create MetalLB memberlist secret
      shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
    
    # Install ingress-nginx
    - name: add ingress-nginx helm repo
      shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      
    - name: run helm update
      shell: helm repo update

    - name: create ingress namespace
      shell: kubectl create namespace ingress-nginx

    - name: install internal ingress controller
      shell: helm upgrade --install internal ingress-nginx/ingress-nginx -f - -n ingress-nginx
      args:
        stdin: |
          controller:
            ingressClass: internal
            electionID: internal
            ingressClassResource:
              name: internal
              enabled: true
              default: true
              controllerValue: "k8s.io/internal-ingress-nginx"
    
    - name: install external ingress controller
      shell: helm upgrade --install external ingress-nginx/ingress-nginx -f - -n ingress-nginx
      args:
        stdin: |
          controller:
            ingressClass: external
            electionID: external
            ingressClassResource:
              name: external
              enabled: true
              default: false
              controllerValue: "k8s.io/internal-ingress-nginx"
            replicaCount: 2
    
    
